In [1]:
import numpy as np
import pandas as pd

# **Creating DataFrame**

In [2]:
# using list
student_data=[
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,50,2]
]

pd.DataFrame(student_data,columns=['iq',"marks","package(in lakhs)"])

    iq  marks  package(in lakhs)
0  100     80                 10
1   90     70                  7
2  120    100                 14
3   80     50                  2

In [35]:
# using dict
Student_dict={
    'name':['nitish','ankit','Shubham','Saurav','Sourya','Shruti'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students=pd.DataFrame(Student_dict)
students.set_index('name',inplace=True)
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
Shubham  120    100       14
Saurav    80     50        2
Sourya     0      0        0
Shruti     0      0        0

In [5]:
# using csv_read
movies=pd.read_csv('/bollywood.csv')
movies

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.00,8576361,26622,2527
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.00,1087320,1129,137
2,3,18-Jul-14,AmitSahniKiList,N,Comedy,10,4.00,572336,586,54
3,4,4-Jan-13,RajdhaniExpress,N,Drama,7,0.35,42626,86,19
4,5,4-Jul-14,BobbyJasoos,N,Comedy,18,10.80,3113427,4512,1224
...,...,...,...,...,...,...,...,...,...,...
144,145,27-Feb-15,DumLagaKeHaisha,N,Comedy,15,30.00,3250917,8185,615
145,146,13-Mar-15,NH10,N,Thriller,13,32.10,5592977,15464,1513
146,147,20-Mar-15,DilliwaliZaalimGirlfriend,N,Comedy,32,12.00,2316047,4289,807
147,148,20-Mar-15,Hunterrr,N,Comedy,5,11.89,4674795,3706,762
148,149,23-May-14,Kochadaiiyaan,HS,Action,150,120.00,4740727,13466,2649

# **DataFrame Attributes and Methods**

In [6]:
# shape
movies.shape

(149, 10)

In [7]:
# dtypes
movies.dtypes

SlNo                     int64
ReleaseDate             object
MovieName               object
ReleaseTime             object
Genre                   object
Budget                   int64
BoxOfficeCollection    float64
YoutubeViews             int64
YoutubeLikes             int64
YoutubeDislikes          int64
dtype: object

In [8]:
# index
movies.index

RangeIndex(start=0, stop=149, step=1)

In [9]:
# columns
movies.columns

Index(['SlNo', 'ReleaseDate', 'MovieName', 'ReleaseTime', 'Genre', 'Budget',
       'BoxOfficeCollection', 'YoutubeViews', 'YoutubeLikes',
       'YoutubeDislikes'],
      dtype='object')

In [10]:
# values
students.values
movies.values

array([[1, '18-Apr-14', '2States', ..., 8576361, 26622, 2527],
       [2, '4-Jan-13', 'TableNo.21', ..., 1087320, 1129, 137],
       [3, '18-Jul-14', 'AmitSahniKiList', ..., 572336, 586, 54],
       ...,
       [147, '20-Mar-15', 'DilliwaliZaalimGirlfriend', ..., 2316047,
        4289, 807],
       [148, '20-Mar-15', 'Hunterrr', ..., 4674795, 3706, 762],
       [149, '23-May-14', 'Kochadaiiyaan', ..., 4740727, 13466, 2649]],
      dtype=object)

In [11]:
# head
movies.head(2)

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.0,8576361,26622,2527
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.0,1087320,1129,137

In [12]:
# tail
movies.tail(2)

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
147,148,20-Mar-15,Hunterrr,N,Comedy,5,11.89,4674795,3706,762
148,149,23-May-14,Kochadaiiyaan,HS,Action,150,120.00,4740727,13466,2649

In [13]:
# sample
movies.sample(3)

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
17,18,6-Jun-14,Filmistaan,HS,Comedy,10,6.0,989096,1608,173
46,47,15-Mar-13,MereDadKiMaruti,N,Comedy,5,11.0,569711,1226,133
57,58,5-Apr-13,ChashmeBaddoor,N,Comedy,20,42.0,166066,2897,283

In [14]:
# info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SlNo                 149 non-null    int64
 1   ReleaseDate          149 non-null    object
 2   MovieName            149 non-null    object
 3   ReleaseTime          149 non-null    object
 4   Genre                149 non-null    object
 5   Budget               149 non-null    int64
 6   BoxOfficeCollection  149 non-null    float64
 7   YoutubeViews         149 non-null    int64
 8   YoutubeLikes         149 non-null    int64
 9   YoutubeDislikes      149 non-null    int64
dtypes: float64(1), int64(5), object(4)
memory usage: 11.8+ KB

In [15]:
# describe
movies.describe()

,SlNo,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
count,149.000000,149.000000,149.000000,1.490000e+02,149.000000,149.000000
mean,75.000000,29.442953,55.667248,3.337920e+06,7877.536913,1207.818792
std,43.156691,28.237981,94.494531,3.504407e+06,12748.047191,1852.692938
min,1.000000,2.000000,0.010000,4.354000e+03,1.000000,1.000000
25%,38.000000,11.000000,8.780000,1.076591e+06,1377.000000,189.000000
50%,75.000000,21.000000,28.000000,2.375050e+06,4111.000000,614.000000
75%,112.000000,35.000000,57.450000,4.550051e+06,9100.000000,1419.000000
max,149.000000,150.000000,735.000000,2.317107e+07,101275.000000,11888.000000

In [16]:
# isnull
movies.isnull().sum()

SlNo                   0
ReleaseDate            0
MovieName              0
ReleaseTime            0
Genre                  0
Budget                 0
BoxOfficeCollection    0
YoutubeViews           0
YoutubeLikes           0
YoutubeDislikes        0
dtype: int64

In [17]:
# duplicated
movies.duplicated().sum()

np.int64(0)

In [18]:
students.duplicated().sum()

np.int64(1)

In [19]:
# rename:not permanent
students.rename(columns={'marks':'percent','package':'lpa'})

    iq  percent  lpa
0  100       80   10
1   90       70    7
2  120      100   14
3   80       50    2
4    0        0    0
5    0        0    0

# **Maths Method**

In [22]:
# sum -> axis argument
students.sum(axis=1)#rowwise sum by default it is column wise

0    190
1    167
2    234
3    132
4      0
5      0
dtype: int64

In [25]:
print(students.std())
students.mean()

iq         52.057660
marks      41.952354
package     5.787918
dtype: float64

iq         65.0
marks      50.0
package     5.5
dtype: float64

# **Selecting cols from a DataFram**

In [28]:
# single cols
# it is a series
print(type(movies['MovieName']))
movies['MovieName']

<class 'pandas.core.series.Series'>

0                        2States
1                     TableNo.21
2                AmitSahniKiList
3                RajdhaniExpress
4                    BobbyJasoos
                 ...
144              DumLagaKeHaisha
145                         NH10
146    DilliwaliZaalimGirlfriend
147                     Hunterrr
148                Kochadaiiyaan
Name: MovieName, Length: 149, dtype: object

In [31]:
# multiple cols
# it will be dataframe
# jis oder me margaya h usse oder me aaiga
print(type(movies[['MovieName','Budget','BoxOfficeCollection']]))
movies[['MovieName','Budget','BoxOfficeCollection']]

<class 'pandas.core.frame.DataFrame'>

                     MovieName  Budget  BoxOfficeCollection
0                      2States      36               104.00
1                   TableNo.21      10                12.00
2              AmitSahniKiList      10                 4.00
3              RajdhaniExpress       7                 0.35
4                  BobbyJasoos      18                10.80
..                         ...     ...                  ...
144            DumLagaKeHaisha      15                30.00
145                       NH10      13                32.10
146  DilliwaliZaalimGirlfriend      32                12.00
147                   Hunterrr       5                11.89
148              Kochadaiiyaan     150               120.00

[149 rows x 3 columns]

# **Selecting R0ws from DataFrame**



*   **iloc** - searches using positions
*   **loc** - searches using index labels

In [36]:
# single row
# its type is pandas series
movies.iloc[0]

SlNo                           1
ReleaseDate            18-Apr-14
MovieName                2States
ReleaseTime                   LW
Genre                    Romance
Budget                        36
BoxOfficeCollection        104.0
YoutubeViews             8576361
YoutubeLikes               26622
YoutubeDislikes             2527
Name: 0, dtype: object

In [37]:
# multiple rows
# its type is dataframe
movies.iloc[0:5]

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.00,8576361,26622,2527
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.00,1087320,1129,137
2,3,18-Jul-14,AmitSahniKiList,N,Comedy,10,4.00,572336,586,54
3,4,4-Jan-13,RajdhaniExpress,N,Drama,7,0.35,42626,86,19
4,5,4-Jul-14,BobbyJasoos,N,Comedy,18,10.80,3113427,4512,1224

In [38]:
movies.iloc[[0,7,9]]

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
0,1,18-Apr-14,2States,LW,Romance,36,104.00,8576361,26622,2527
7,8,11-Jan-13,MatruKiBijleeKaMandola,N,Comedy,33,40.00,2435283,4326,647
9,10,11-Jan-13,Gangoobai,N,Drama,2,0.01,4354,1,1

In [39]:
# loc
students.loc['nitish']

iq         100
marks       80
package     10
Name: nitish, dtype: int64

In [40]:
# last waala include hota h
students.loc['nitish':'Shubham']

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
Shubham  120    100       14

In [41]:
# ye same kamm ham log iloc se bhi kr skte h
students.loc[['Shubham','Saurav','nitish']]

          iq  marks  package
name
Shubham  120    100       14
Saurav    80     50        2
nitish   100     80       10

# Selecting both rows and cols

In [42]:
movies.iloc[0:3,0:3]

   SlNo ReleaseDate        MovieName
0     1   18-Apr-14          2States
1     2    4-Jan-13       TableNo.21
2     3   18-Jul-14  AmitSahniKiList

In [43]:
movies.loc[0:2,'MovieName':'BoxOfficeCollection']

         MovieName ReleaseTime     Genre  Budget  BoxOfficeCollection
0          2States          LW   Romance      36                104.0
1       TableNo.21           N  Thriller      10                 12.0
2  AmitSahniKiList           N    Comedy      10                  4.0

# **Filtering DataFrame**

In [44]:
ipl=pd.read_csv('/matches.csv')
ipl

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,5/4/2017,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,6/4/2017,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,7/4/2017,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,8/4/2017,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,8/4/2017,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,22/05/16,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,24/05/16,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,25/05/16,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,27/05/16,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,29/05/16,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [51]:
# city=ipl['city']=='Delhi'
# delhi=ipl[city]
# delhi[['date','winner']]
ipl[ipl['city']=='Delhi'][['date','winner']]

          date                       winner
14    15/04/17             Delhi Daredevils
17    17/04/17        Kolkata Knight Riders
38    2/5/2017             Delhi Daredevils
40    4/5/2017             Delhi Daredevils
43    6/5/2017               Mumbai Indians
50   12/5/2017             Delhi Daredevils
54    14/05/17  Royal Challengers Bangalore
61    19/04/08             Delhi Daredevils
75    30/04/08             Delhi Daredevils
86    8/5/2008          Chennai Super Kings
97    15/05/08             Delhi Daredevils
99    17/05/08              Kings XI Punjab
108   24/05/08             Delhi Daredevils
182   17/03/10               Mumbai Indians
184   19/03/10          Chennai Super Kings
199   29/03/10             Delhi Daredevils
202   31/03/10             Delhi Daredevils
208   4/4/2010             Delhi Daredevils
217  11/4/2010              Kings XI Punjab
228   18/04/10              Deccan Chargers
237  10/4/2011               Mumbai Indians
252   19/04/11              Deccan Chargers
258   23/04/11             Delhi Daredevils
262   26/04/11  Royal Challengers Bangalore
265   28/04/11        Kolkata Knight Riders
273   2/5/2011         Kochi Tuskers Kerala
300   21/05/11                          NaN
317  10/4/2012             Delhi Daredevils
322   19/04/12             Delhi Daredevils
334   21/04/12                Pune Warriors
341   27/04/12             Delhi Daredevils
344   29/04/12             Delhi Daredevils
356   7/5/2012        Kolkata Knight Riders
368   15/05/12             Delhi Daredevils
371   17/05/12  Royal Challengers Bangalore
384   6/4/2013             Rajasthan Royals
393  12/4/2013          Sunrisers Hyderabad
403   18/04/13          Chennai Super Kings
407   21/04/13             Delhi Daredevils
437  10/5/2013  Royal Challengers Bangalore
442   23/04/13              Kings XI Punjab
453   21/05/13          Chennai Super Kings
454   22/05/13             Rajasthan Royals
479   3/5/2014             Rajasthan Royals
482   5/5/2014          Chennai Super Kings
484   7/5/2014        Kolkata Knight Riders
488  10/5/2014          Sunrisers Hyderabad
501   19/05/14              Kings XI Punjab
522  12/4/2015             Rajasthan Royals
534   20/04/15        Kolkata Knight Riders
538   23/04/15             Delhi Daredevils
542   26/04/15  Royal Challengers Bangalore
547   1/5/2015             Delhi Daredevils
582   15/04/16             Delhi Daredevils
592   23/04/16             Delhi Daredevils
598   27/04/16                Gujarat Lions
601   30/04/16             Delhi Daredevils
608   5/5/2016      Rising Pune Supergiants
633   25/05/16          Sunrisers Hyderabad
634   27/05/16          Sunrisers Hyderabad

In [57]:
ipl[ipl['result']!='normal'][['date','team1','team2','result']].shape[0]

10

In [70]:
ipl[(ipl['city']=='Kolkata') & (ipl['winner']=='Chennai Super Kings')].shape[0]

4

In [74]:
tosswinner=ipl[ipl['toss_winner'] == ipl['winner']].shape[0]
totalmatches=ipl.shape[0]
(tosswinner*100)/totalmatches

51.100628930817614

In [78]:
# for more than one option in the particular column
# or movies['Genre'].str.contains('Action)
movies[(movies['Genre'].str.split('|').apply(lambda x: 'Action' in x)) &(movies['Budget']> 30)]

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes
22,23,14-Feb-14,Gunday,N,Action,50,76.70,3503887,8383,1419
35,36,22-Feb-13,ZillaGhaziabad,N,Action,36,16.00,1551786,1753,619
36,37,6-Jun-14,Holiday,HS,Action,50,129.00,6841635,14182,1997
41,42,24-Jan-14,JaiHo,N,Action,120,111.00,868743,2783,404
43,44,25-Jul-14,Kick,N,Action,100,377.00,18986221,101275,10066
54,55,29-Mar-13,Himmatwala,N,Action,50,100.00,2501277,1,1
78,79,15-Aug-14,SinghamReturns,LW,Action,90,200.00,8287587,20011,2899
91,92,5-Dec-14,ActionJackson,N,Action,90,57.45,13279636,19240,3859
92,93,2-Oct-14,BangBang,FS,Action,140,340.00,15889811,61805,6283
119,120,1-Nov-13,Krrish3,FS,Action,115,300.00,23171067,72070,11888
130,131,6-Sep-13,Zanjeer,LW,Action,75,18.20,2539431,5634,922
136,137,9-Jan-15,Tevar,N,Action,40,56.00,6132407,11241,1729
138,139,23-Jan-15,Baby,N,Action,60,125.00,7968156,29246,2426
148,149,23-May-14,Kochadaiiyaan,HS,Action,150,120.00,4740727,13466,2649

# Adding new **cols**

In [80]:
# completely new
movies['country']='India'
movies.head(2)

,SlNo,ReleaseDate,MovieName,ReleaseTime,Genre,Budget,BoxOfficeCollection,YoutubeViews,YoutubeLikes,YoutubeDislikes,country
0,1,18-Apr-14,2States,LW,Romance,36,104.0,8576361,26622,2527,India
1,2,4-Jan-13,TableNo.21,N,Thriller,10,12.0,1087320,1129,137,India

In [ ]:
# from existing ones
# movies['Actor'].str.slit('|').apply(lambda x:x[0])

# **astype**

In [83]:
movies['Budget']=movies['Budget'].astype(np.int32)

In [84]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   SlNo                 149 non-null    int64
 1   ReleaseDate          149 non-null    object
 2   MovieName            149 non-null    object
 3   ReleaseTime          149 non-null    object
 4   Genre                149 non-null    object
 5   Budget               149 non-null    int32
 6   BoxOfficeCollection  149 non-null    float64
 7   YoutubeViews         149 non-null    int64
 8   YoutubeLikes         149 non-null    int64
 9   YoutubeDislikes      149 non-null    int64
 10  country              149 non-null    object
dtypes: float64(1), int32(1), int64(4), object(5)
memory usage: 12.4+ KB